apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ADMINER_DEFAULT_SYSTEM
              value: pgsql
            - name: ADMINER_DESIGN
              value: nette
            - name: ADMINER_DEFAULT_SERVER
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: PGHOST
          ports:
            - name: http
              containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30005
