##
 # Secrets used to initialize / connect to PostgreSQL image
 # Created for project Lobbier: https://github.com/BillMyres/Lobbier
 # @author Thomas vanBommel
 # @since 11-2020
 ##

# posrgres secrets
apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
stringData:
  PGHOST: "postgres-service"
  PGPORT: "5432"
  PGUSER: "lobbier"
  PGPASSWORD: "12345"
  PGDATABASE: "lobbier_users"
